blank_issues_enabled: true
contact_links:
  - name: 📄 Docs
    url: https://docs.ultralytics.com/
    about: Full Ultralytics Documentation
  - name: 💬 Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: 🎧 Discord
    url: https://discord.gg/2wNGbc6g9X
    about: Ask on Ultralytics Discord
