name: Check Broken links

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # runs at 00:00 UTC every day

jobs:
  Links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Markdown and HTML links with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: >
            docker run --rm -v "${PWD}:/workspace" lycheeverse/lychee --accept 429,999 --exclude-loopback --exclude twitter.com --exclude-path '**/ci.yaml' --exclude-mail './**/*.md' './**/*.html'

      - name: Test Markdown, HTML, YAML, Python and Notebook links with retry
        if: github.event_name == 'workflow_dispatch'
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: >
            docker run --rm -v "${PWD}:/workspace" lycheeverse/lychee --accept 429,999 --exclude-loopback --exclude twitter.com,url.com --exclude-path '**/ci.yaml' --exclude-mail './**/*.md' './**/*.html' './**/*.yml' './**/*.yaml' './**/*.py' './**/*.ipynb'
